### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by maxgrossman** [developmentseed/doc-seed#1]
# Goal

Make a lightweight, easily reproducible microsite used for technical reports.

## What

Microsite w/ content managed in a single markdown file. Markdown + YAML front matter is compiled and rendered as HTML. YFM + Markdown header tags help decide where to render what.

## How

- Put markdown file and Jekyll inspired page components (almost like pseudo includes) in an app folder.
- Write report in markdown file
- call a build command that runs a build.js file that interprets the markdown/front matter and makes the HTML
  - this would be run as gulp task alongside other tasks that move assets over to a microsite folder

## Plan

- week of 6/30: make page components and build.js script and test template locally
- week of 7/07: add in ui styles

**Comment by olafveerman** [comment]
Some more suggestions to scope the MVP:

- one-pager with section titles
- 1 level nav
- mobile first
- prose area that reads well and supports media
- clear and subtle DevSeed branding, with space for branding of client/report

Beyond MVP:

- choice of one-page vs. multi-page
- 2 level nav
- print styles

Does this make sense? Anything I missed @ricardomestre

**Comment by maxgrossman** [comment]
@ricardomestre I pulled in ui-seed as a dependency for making the page components. 
To make sure we are mobile friendly first, what other resources would you suggest we use?

**Comment by ricardoduplos** [comment]
@maxgrossman That sounds great. I can't think about other resources. Note that ui-seed is still a work in progress - but I'm working on it.

**Comment by ricardoduplos** [comment]
@olafveerman 👍

**Comment by maxgrossman** [comment]
@ricardomestre sounds good. Looking forward to using / letting you know how it goes
