### ISSUE TITLE
Architecture proposal

### ISSUE THREAD

**Issue by danielfdsilva** [developmentseed/doc-seed#18]
# What we need?

Doc seed is a simple documentation/report site. The architecture we choose must be able to support some basic features:
- Render one piece of content per page with a unique and customizable(?) url. Each piece of content must belong to a section, have a title and a body.
- Render a navigation dynamically with content grouped by section.
- Allow pages to have subpages which will be displayed in the navigation (?)
- Allow previous/next navigation between content pieces.
- Allow basic customization of site title, description, base url...

The visual direction can be found [here](https://github.com/developmentseed/doc-seed/issues/17)

### Future features
Although we may not implement these right now, we should have them in mind when choosing the architecture and make decisions that don't hinder their future implementation.

- Ability to include standalone template pages and other content types. Eg: Tech demo pages.

## Static site generators

I had a look at [Hexo](https://hexo.io) but it seemed overly complicated and too bloated for our use case.

Another framework I looked at was [Metalsmith](http://www.metalsmith.io/) and this one is very promising. It's not exactly a static site generator but "just an abstraction for manipulating a directory of files". It has a pluggable system of plugins that manipulates the content how we see fit.
Using these plugins we can easily build a navigation tree, add information about previous/next posts, render markdown, etc. Since everything is a plugin we can pick whatever we want to render the content, even customize our own.

## React

We could also follow a react approach where we load and render the markdown asynchronously. Advantages here would be more control over how everything works, but there would be a lot more work involved in setting up and modifying the whole structure.

# Final thoughts

I think something like Metalsmith is exactly what we want. Gives us the power of plugins, either our own or from the community and doesn't make assumptions about how content should be structured or managed.

Follows a proposal on how to structure the project.

- Use a project seed style folder structure:
```
  app/
    assets/
      scripts/
      styles/
    content/
      posts/
    layouts/ --> Probably will depend on the layout plugin used
```
- Adapt/simplify the gulp file to include the site generation and assets compilation.
- Include UI Seed if possible. @ricardomestre
- Use the post front matter to define what section the content belongs to as well as what's the parent page.

I'll investigate some more into Metalsmith and what plugins / workflows we can use to achieve the mvp, namely:
- How to render the navigation tree
- How to use a settings file to store things like site name, base url... (including dev overrides to this)
- Figure out the best layout plugin to use

Thoughts @olafveerman @maxgrossman @ricardomestre ?

**Comment by maxgrossman** [comment]
@danielfdsilva @olafveerman @ricardomestre @eliLitwack 

I too am pro Metalsmith. Seems like a tool that we can use only what we want of without being bound by the rules of how the directory needs to be set up like w/jekyll or hexo. 

It also has a webpack-ish feel to it that is nice (there is a place where your pre-web files live. Then you, with plugins, make them the files web-ready).

Plus the react plugins I saw on its site makes it seem as though post-mvp doc-seed will be easily modified. 

My only concern is that writing a report across multiple files might not be natural. 

If others share this concern  we could break bend the rules of yfm and write all of the content in one big markdown file where sections are separated by yam like...

```
---
section: Main Section
title: MainSection Title
---

words
--- 
section: Sub-Section
title: SubSection Title
---

ui-seed is cool. 
```

we could then have a small pre-build script that breaks that large file up by those yfm tags and writes out small files for each section that include the yam and the content for each section. These small files would sit in a _posts or even _sections folder that we'd render as our doc-seed site with Metalsmith.

**Comment by danielfdsilva** [comment]
@maxgrossman I understand what you mean, but I assume that once the content is written it won't be changes drastically and it's simpler to organize in multiple files.
One could start writing it in one file and split it when publishing the content.
